import { apiGET, apiGETAuth } from '@/utils/apiUtils';
import { checkToken } from '@/utils/cookieUtils';
import { Box, Button } from '@chakra-ui/react';
import Head from 'next/head'
import { useEffect, useState } from 'react';

export default function Home() {

    const [courses, setCourses] = useState<any[]>([]);
    const [logged, setLogged] = useState(false);

    const redirect = (path: string) => {
        const currentUrl = window.location.href;
        const baseUrl = currentUrl.split('/').slice(0, 3).join('/');
        const absoluteUrl = `${baseUrl}${path}`;
        window.location.href = absoluteUrl;
    }

    useEffect(() => {
        const logged = checkToken();
        setLogged(logged);
        if (logged) {
            apiGET("/courses").then((data: any) => {
                setCourses(data);
            }) 
        } else {
            apiGETAuth("/courses").then((data: any) => {
                setCourses(data);
            }) 
        }
    }, []);

    return (
        <>
            <Head>
                <title>Dev</title> <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box m={2}>
                <Box>
                    {logged &&
                        ( "User: " + localStorage.getItem("username") )
                    }
                    {!logged &&
                        <Button onClick={() => {redirect("/login")}}>Login</Button>
                    }
                </Box>
                <Box fontSize={25}>Courses</Box>
                <Box>
                    {courses?.map((course: any, index: number) => (
                        <Box key={index} cursor={"pointer"} onClick={() => redirect("/course?id=" + course.id)}>
                            {course.title}
                        </Box>
                    ))}
                </Box>
            </Box>
        </>
    )
}
