import { apiGET, apiPOST } from '@/utils/apiUtils';
import { setCookie } from '@/utils/cookieUtils';
import { Box, Button, FormControl, FormLabel, Input } from '@chakra-ui/react';
import Head from 'next/head'
import { useEffect, useState } from 'react';

export default function Login() {

    const [values, setValues] = useState({
        username: '',
        password: ''
    })

    const redirect = (path: string) => {
        const currentUrl = window.location.href;
        const baseUrl = currentUrl.split('/').slice(0, 3).join('/');
        const absoluteUrl = `${baseUrl}${path}`;
        window.location.href = absoluteUrl;
    }
    
    const attemptLogin = () => {
        apiPOST("/authenticate", { username: values.username, password: values.password }).then((data: any) => {
            setCookie("token", data.access_token, 10);
            localStorage.setItem("username", values.username);
            redirect("/");
        });
    }
    

    return (
        <>
            <Head>
                <title>Dev</title> <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box m={2}>
                <FormControl>
                    <FormLabel>Username</FormLabel>
                    <Input placeholder='Username' value={values.username} onChange={(e) => setValues({...values, username: e.target.value})} />
                </FormControl>
                <FormControl>
                    <FormLabel>Password</FormLabel>
                    <Input type="password" placeholder='Password' value={values.password} onChange={(e) => setValues({...values, password: e.target.value})}/>
                </FormControl>
                <Button onClick={() => {attemptLogin()}}>Login</Button>
            </Box>
        </>
    )
}
